#' @export
allowed_args <- list(
  "nTime" = "total simulation duration (Days), if drug administration is beyond nTime this will trigger a warning message",
  "nIterations" = "number of iterations in bootstrap process, should be > 100, and generally < 1000",
  "nPatients" = "number of patients per population [size 1000 x 4 drugs => ~6GB on 64bit Intel i5]",
  "nPopulations" = "number of distinct patient populations to generate. If >1 then bootstrap is OFF",
  "nThreads" = "concurrent processing threads for parallel program execution",
  "therapyStart" = "time point for drug administration start",
  "disease" = "disease configuration option, do not change",
  "kMax" = "time steps per day (hourly), do not change",
  "isSavePatientResults" = "then will save selected simulation data for EACH patient. Note: adds significant processing overhead",
  "isSavePopulationResults" = "enables saving of simulation results summary statistics ",
  "isSaveAdhDose" = "save adherence and dosing metrics",
  "isSaveConc" = "save PK concentration metrics",
  "isSaveConcKill" = "save PK kill and growth factors [0..1]",
  "isSaveImmune" = "save Immune system metrics (12 values)",
  "isSaveMacro" = "save Macrophage metrics (3 types)",
  "isSaveBact" = "save Bacteria (wild-type strains)",
  "isSaveBactRes" = "save Resistant bacteria strain metrics",
  "isSaveOutcome" = "save population Outcome metrics",
  "isSaveEffect" = "save drug kill effect metrics",
  "isBootstrap" = "is bootstrap simulation (calculate confidence intervals)",
  "isAdherence" = "calculate adherence vector",
  "isDrugDose" = "calculate drug dose vector",
  "isConcentration" = "calculate drug PK vector",
  "isSolution" = "calculate PD and immune system vector",
  "isOutcome" = "calculate population therapy outcome",
  "isDrugEffect" = "calculate drug kill effects",
  "isResistance" = "bacterial resistance enabled",
  "isGranuloma" = "granuloma dynamics enabled ",
  "isImmuneKill" = "immune system killing enabled",
  "isPersistance" = "bacterial persistance state (set to 1)",
  "isClearResist" = "then resistant bacteria is cleared when falls below defined threshold",
  "isGranImmuneKill" = "immune killing inside granuloma",
  "isGranulomaInfec" = "macrophages in granuloma get infected",
  "isGradualDiffusion" = "dynamic drug diffusion into granuloma based on parameters rise50, fall50, and multiplier. =0 immediate drug diffusion into granuloma based on parameter GRfactor",
  "persistTime" = "time span for persistance status",
  "initialValueStdv" = "CV applied for variance for starting parameters for ODE system",
  "parameterStdv" = "CV applied for variance of immune system variables",
  "timeStepStdv" = "CV applied at each time step",
  "adherenceType1" = "adherence during intensive therapy period",
  "adherenceType2" = "adherence during continuation therapy",
  "adherenceMEMS" = "adherence read from MEMS data",
  "memsFile" = "MEMS data file used for simulation",
  "adherenceSwitchDay" = "day for switch between adh type 1 and 2",
  "adherenceMean" = "mean population patient adherence",
  "adherenceStdv" = "CV for patient adherence",
  "adherenceStdvDay" = "variance (CV) in patient adherence per day step",
  "shareLowAcetylators" = "share in population with low acetylators (INH)",
  "immuneMean" = "average patient immune system status [0..1]",
  "immuneStdv" = "CV for immune status",
  "granulomaGrowth" = "relative bacterial growth rate in granuloma",
  "granulomaKill" = "drug PD effectiveness inside granuloma",
  "granulomaGrowthInh" = "reduced growth inhibition by drugs in granuloma (defined as 1/factor)",
  "granulomaFormation" = "rate for granuloma formation, which is multiplied with bacterial load",
  "granulomaInfectionRate" = "factor defining rate of macrophage infection inside granuloma [0..1]",
  "granulomaBreakup" = "then granuloma breakup is active",
  "bactThreshold" = "limit to filter out low levels of bacteria",
  "bactThresholdRes" = "limit to filter out low levels of resistant bact",
  "growthLimit" = "limit for considered non-persisting bacteria",
  "freeBactLevel" = "max bacteria level outside of granuloma to be considered Cleared TB [CFU/ml]",
  "latentBactLevel" = "max bacteria threshold outside of granuloma to be considered Latent TB, assuming level of extracellular bacteria is below threshold for acute infection [CFU/ml]",
  "infI" = "initial bacterial in extracellular non-granuloma compartment [CFU/ml]",
  "infII" = "initial bacterial in intracellular non-granuloma compartment  [CFU/ml]",
  "infIII" = "initial bacterial in extracellular granuloma compartment [CFU/ml]",
  "infIV" = "initial bacterial in intracellular granuloma compartment [CFU/ml]",
  "resistanceRatio" = "ratio of naturally occuring resistant strains",
  "resistanceFitness" = "relative fitness of mono-drug resistant bacteria",
  "defaultTherapy" = "default therapy at launch of program")
class(allowed_args) <- c("list", "allowed_args")

print.allowed_args <- function(x) {
  for(i in seq(names(x))) {
    cat(paste0("- '", names(x)[i], "': ", x[[names(x)[i]]], "\n"))
  }
}
