#' @export
allowed_args <- list(
  "nTime" = "total simulation duration (Days), if drug administration is beyond nTime this will trigger a warning message",
  "nIterations" = "number of iterations in bootstrap process, should be > 100, and generally < 1000",
  "nPatients" = "number of patients per population [size 1000 x 4 drugs => ~6GB on 64bit Intel i5]",
  "nPopulations" = "number of distinct patient populations to generate. If >1 then boostrap is OFF",
  "nThreads" = "concurrent processing threads for parallel program execution",
  "therapyStart" = "time point for drug administration start",
  "disease" = "disease configuration option, do not change",
  "kMax" = "time steps per day (hourly), do not change",
  "isSavePatientResults" = "=1 then will save selected simulation data for EACH patient. Note: adds significant processing overhead",
  "isSavePopulationResults" = "=1 enables saving of simulation results summary statistics ",
  "isSaveAdhDose" = "=1 save adherence and dosing metrics",
  "isSaveConc" = "=1 save PK concentration metrics",
  "isSaveConcKill" = "=1 save PK kill and growth factors [0..1]",
  "isSaveImmune" = "=1 save Immune system metrics (12 values)",
  "isSaveMacro" = "=1 save Macrophage metrics (3 types)",
  "isSaveBact" = "=1 save Bacteria (wild-type strains)",
  "isSaveBactRes" = "=1 save Resistant bacteria strain metrics",
  "isSaveOutcome" = "=1 save population Outcome metrics",
  "isSaveEffect" = "=1 save drug kill effect metrics",
  "isBootstrap" = "?",
  "isAdherence" = "=1 calculate adherence vector",
  "isDrugDose" = "=1 calculate drug dose vector",
  "isConcentration" = "=1 calculate drug PK vector",
  "isSolution" = "=1 calculate PD and immune system vector",
  "isOutcome" = "=1 calculate population therapy outcome",
  "isDrugEffect" = "=1 calculate drug kill effects",
  "isResistance" = "=1 bacterial resistance enabled",
  "isGranuloma" = "=1 granuloma dynamics enabled ",
  "isImmuneKill" = "=1 immune system killing enabled",
  "isPersistance" = "=1 bacterial persistance state (set to 1)",
  "isClearResist" = "=1 then resistant bacteria is cleared when falls below defined threshold",
  "isGranImmuneKill" = "=1 immune killing inside granuloma",
  "isGranulomaInfec" = "=1 macrophages in granuloma get infected",
  "isGradualDiffusion" = "=1 dynamic drug diffusion into granuloma based on parameters rise50, fall50, and multiplier. =0 immediate drug diffusion into granuloma based on parameter GRfactor",
  "persistTime" = "time span for persistance status",
  "initialValueStdv" = "standard error applied for variance for starting parameters for ODE system",
  "parameterStdv" = "standard error applied for variance of immune system variables",
  "timeStepStdv" = "standard error applied at each time step",
  "adherenceType1" = "adherence during intensive therapy period",
  "adherenceType2" = "adherence during continuation therapy",
  "adherenceMEMS" = "adherence read from MEMS data",
  "memsFile" = "MEMS data file used for simulation",
  "adherenceSwitchDay" = "day for switch between adh type 1 and 2",
  "adherenceMean" = "mean population patient adherence",
  "adherenceStdv" = "standard error for patient adherence",
  "adherenceStdvDay" = "variance in patient adherence per day step",
  "shareLowAcetylators" = "share in population with low acetylators (INH)",
  "immuneMean" = "average patient immune system status [0..1]",
  "immuneStdv" = "standard error variance for immune status",
  "granulomaGrowth" = "relative bacterial growth rate in granuloma",
  "granulomaKill" = "drug PD effectiveness inside granuloma",
  "granulomaGrowthInh" = "reduced growth inhibition by drugs in granuloma (defined as 1/factor)",
  "granulomaFormation" = "rate for granuloma formation, which is multiplied with bacterial load",
  "granulomaInfectionRate" = "factor defining rate of macrophage infection inside granuloma [0..1]",
  "granulomaBreakup" = "=1 then granuloma breakup is active",
  "bactThreshold" = "limit to filter out low levels of bacteria",
  "bactThresholdRes" = "limit to filter out low levels of resistant bact",
  "growthLimit" = "limit for considered non-persisting bacteria",
  "freeBactLevel" = "max bacteria level outside of granuloma to be considered Cleared TB",
  "latentBactLevel" = "max bacteria threshold outside of granuloma to be considered Latent TB",
  "infI" = "initial bacterial in compartment 1 [CFU/ml]",
  "infII" = "initial bacterial in compartment 2 [CFU/ml]",
  "infIII" = "initial bacterial in compartment 3 [CFU/ml]",
  "infIV" = "initial bacterial in compartment 4 [CFU/ml]",
  "resistanceRatio" = "ratio of naturally occuring resistant strains",
  "resistanceFitness" = "relative fitness of mono-drug resistant bacteria",
  "defaultTherapy" = "default therapy at launch of program")
class(allowed_args) <- c("list", "allowed_args")

print.allowed_args <- function(x) {
  for(i in seq(names(x))) {
    cat(paste0("- '", names(x)[i], "': ", x[[names(x)[i]]], "\n"))
  }
}
